woorifisa-projects/GoodFriends

frontend/src/App.vue, frontend/src/components/profile/DefaultMyPage.vue, frontend/src/layouts/DefaultHeader.vue, frontend/src/layouts/DefaultLayout.vue, frontend/src/router/index.ts, frontend/src/views/ProfileView.vue
Close #31 
프로필페이지를 구현한다.
html, css 작업이 대부분입니다. 혹시 이해가 되지 않는 부분 있으면 적어주세요!
=> [프로필 페이지] 프로필 페이지를 구현한다.

frontend/src/components/profile/DefaultMyPage.vue, frontend/src/components/profile/ItemList.vue, frontend/src/router/index.ts, frontend/src/types/Profile.ts, frontend/src/views/PurchaseView.vue, frontend/src/views/SellView.vue
>
Close #38 
>
- 판매목록 및 구매 목록 페이지 구현
- 프로필 페이지 내부 페이지 이동 사이드바 구현
>
=> [프로필 페이지] 구매 페이지 및 판매 페이지를 구현한다.

frontend/src/router/index.ts, frontend/src/views/AdminLogin.vue
>
Close #41 
>
관리자가 로그인하는 페이지를 구현했습니다.
관리자 로그인 api가 구현된 후 api연결하는 작업이 필요합니다.
디자인 추천받습니다!
=> [관리자 페이지] 로그인 페이지를 구현한다.

backend/src/main/java/woorifisa/goodfriends/backend/BackendApplication.java, backend/src/main/java/woorifisa/goodfriends/backend/auth/controller/OAuthLoginController.java, backend/src/main/java/woorifisa/goodfriends/backend/auth/dto/GoogleOAuthClient.java, backend/src/main/java/woorifisa/goodfriends/backend/auth/dto/OAuthConfig.java, backend/src/main/java/woorifisa/goodfriends/backend/auth/service/OAuthLoginService.java
Close #12 
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요.
=> 소셜 로그인을 이용하여 로그인 기능을 구현한다.

.gitignore
MySQL 관련 yml 파일 .gitignore에 추가했습니다.
- application.yml
- application-db.yml
- application-oauth.yml
해당 파일에 대한 내용은 slack - backend 채널에 고정두겠습니다!
=> MySQL 관련 yml 파일 .gitignore에 추가

frontend/package.json
Close #50 
배포하기 위한 EC2 메인 서버를 구축하기 위해 package.json을 수정했습니다.
=> 프론트엔드 EC2서버 배포하기 위해 package.json 수정

backend/src/main/java/woorifisa/goodfriends/backend/admin/domain/Admin.java, backend/src/main/java/woorifisa/goodfriends/backend/admin/dto/request/AdminLoginRequest.java, backend/src/main/java/woorifisa/goodfriends/backend/global/config/webconfig/WebConfig.java, frontend/package-lock.json, frontend/package.json, frontend/src/apis/adminLogin.ts, frontend/src/views/AdminLogin.vue
Close #48
피니아에 대해 공부하여 액세스 토큰 저장 방식을 추후 변경하도록 하겠습니다.
=> 백엔드 관리자 자체 로그인 기능을 프론트엔드 로그인 페이지와 연동하여 동작되도록 구현한다.

frontend/src/layouts/admin/DefaultSide.vue
Close #63 
- 관리자 페이지 사이드바 구현했습니다.
- 버튼 : 로고, 로그 관리, 사용자 관리, 상품 관리, 신고 관리
=> [관리자 페이지] 사이드바 컴포넌트를 구현한다.

frontend/src/router/index.ts, frontend/src/views/HomeView.vue, frontend/src/views/ProductView.vue
Close #61 
- 상품 상세 페이지 구현
- 유저에 따라 버튼이 다르게 보이도록 구현
- 작성자: 수정하기 삭제하기
- 작성자 외: 신고하기
- 이미지가 여러개일 경우 버튼을 눌러 이미지 변경
아직은 작성자인지 아닌지 판단이 불가능해 랜덤으로 작성자인지 아닌지 구별하게 햇습니다~
=> [사용자 페이지] 상품 상세 페이지를 구현한다.

frontend/src/components/CommonTable.vue, frontend/src/types/table.ts
Close #70
- props로 data, headerText, dataKey 전달시 표 렌더링
- data: [ { id:number, [key:string :string} ]  형식
- headerText: { data-key: 화면에 보일 텍스트 }
- dataKey: data의 key 모임
=> Feat/70 (관리자 페이지에서 사용할 공통 컴포넌트 구현)

frontend/src/components/CommonModal.vue
Close #77
- slot 으로 구현하여 모달창 내부에 들어갈 html 조작 가능
- props로 isVisible 전달
- 해당 변수는 모달창이 화면에 보이는지를 결정하는 boolean 변수
- emit으로 updateVisible
- 해당 함수는 모달창 외부를 클릭했을 때 모달창이 닫히도록 isVisible 변수를 변경해주는 함수
- 해당 함수는 인자값으로 stauts를 받아야함
```javascript
const updateVisible = (status: boolean) => {
isVisible.value = status;
};
```
=> Feat/77(공통 컴포넌트 모달창구현)

frontend/src/router/index.ts, frontend/src/views/NotFoundView.vue
Close #79 
라우터에 등록되지 않은 페이지 접근시 404페이지로 리다이렉트
=> feat/79(404페이지 구현)

frontend/src/constants/strings/admin.ts, frontend/src/layouts/admin/DefaultSide.vue, frontend/src/views/EditUserInfoView.vue
Close #82 
사용자 정보수정 페이지를 구현하였습니다.
=> [관리자 페이지] 사용자 정보수정 페이지를 구현한다

frontend/src/components/ProductCard.vue, frontend/src/components/product/EditProduct.vue, frontend/src/components/profile/DefaultMyPage.vue, frontend/src/components/profile/ItemList.vue, frontend/src/layouts/DefaultFooter.vue, frontend/src/layouts/DefaultHeader.vue, frontend/src/layouts/DefaultLayout.vue, frontend/src/types/product.ts, frontend/src/views/HomeView.vue, frontend/src/views/NotFoundView.vue, frontend/src/views/ProductView.vue, frontend/src/views/ProfileView.vue, frontend/src/views/PurchaseView.vue
=> Feat/81(반응형 구현)

frontend/src/components/OrderModal.vue, frontend/src/constants/strings/product.ts, frontend/src/utils/date.ts, frontend/src/views/ProductView.vue
Close #85 
- 구매자가 구매하기 버튼 클릭시 주문서 작성 모달창 띄우기
- 올바르지 않은 날짜, 시간 입력시 제출 막는 기능
=> Feat/85(주문 모달창 구현)

frontend/src/constants/strings/product.ts, frontend/src/router/index.ts, frontend/src/views/OrderView.vue, frontend/src/views/ProductView.vue
Close #92 
판매자가 자신의 물건에 들어온 주문서를 볼 수 있는 페이지 구현
=> Feat/92(주문서 목록 페이지 구현)

frontend/src/components/ProductDetailByAdmin.vue, frontend/src/constants/strings/admin.ts, frontend/src/layouts/admin/DefaultSide.vue, frontend/src/router/index.ts, frontend/src/views/AddProductByAdminView.vue, frontend/src/views/EditProductByAdminView.vue
Close #88 
- 상품 수정 페이지와 상품 등록 페이지에 들어가는 요소들을 공통컴포넌트화 하였습니다.
- 상품 수정/관리 페이지를 개발하였습니다.
>
- 개발한 페이지 예시 사진)
=> Feature/88([관리자 페이지] 상품 등록/수정 페이지를 개발한다)

backend/src/main/java/woorifisa/goodfriends/backend/product/application/ProductService.java, backend/src/main/java/woorifisa/goodfriends/backend/product/domain/Product.java, backend/src/main/java/woorifisa/goodfriends/backend/product/dto/response/ProductSaveResponse.java, backend/src/main/java/woorifisa/goodfriends/backend/product/dto/response/ProductSearchResponse.java, backend/src/main/java/woorifisa/goodfriends/backend/product/dto/response/ProductUpdateResponse.java, backend/src/main/java/woorifisa/goodfriends/backend/product/dto/response/ProductViewAllResponse.java, backend/src/main/java/woorifisa/goodfriends/backend/product/dto/response/ProductViewOneResponse.java, backend/src/main/java/woorifisa/goodfriends/backend/product/presentation/ProductController.java
Close #90 
전체 상품 조회 및 상세 상품 조회용 dto명 이대로 괜찮은지 확인 부탁드려요!
현재 코드는 인가 부분과 상품 이미지에 대한 구현은 안되어있는 상태입니다!
=> Feature/90(전체 상품 조회 및 상세 상품 조회 기능을 구현)

frontend/src/App.vue, frontend/src/components/ProductDetailByAdmin.vue, frontend/src/components/product/EditProduct.vue, frontend/src/components/profile/FilterList.vue, frontend/src/components/profile/ItemList.vue, frontend/src/types/product.ts, frontend/src/views/user/profile/PurchaseView.vue, frontend/src/views/user/profile/SellView.vue
Close #102
프로필의 구매/판매목록 페이지에 상태별 필터링 할 수 있는 버튼 추가
색상이나 모양에 대한 좋은 의견 있으면 알려주세요!
=> Feat/102(프로필에서 상품 상태에 따른 필터링)

frontend/src/components/CommonTable.vue, frontend/src/layouts/admin/DefaultSide.vue, frontend/src/router/index.ts, frontend/src/views/admin/ManageLogView.vue
Close #105 
- 사이드바에서 '로그 관리' 버튼을 눌렀을시 해당화면으로 이동하도록 하였습니다.
- 로그관리 화면에서 임시 더미데이터로 리스트업 되도록 구현하였습니다.
- 리스트가 많으면 스크롤으로 내려서 볼 수 있도록 적용하였습니다.
>
=> Feature/105([관리자 페이지] 로그 관리 페이지를 개발한다.)

frontend/src/views/user/HomeView.vue
=> Fix/107(배너 뒤로가기 버튼 오류 수정)

frontend/src/layouts/admin/DefaultSide.vue, frontend/src/router/index.ts, frontend/src/views/admin/ManageDeclarationView.vue
Close #118 
- 사이드바에서 신고 관리 메뉴를 누를 시 해당 페이지로 이동합니다. -> 완료
- 신고내용들을 관리자가 볼 수 있습니다. -> 완료
>
=> Feature/118([관리자 페이지] 신고 관리 페이지를 개발한다.)

frontend/src/layouts/admin/DefaultSide.vue, frontend/src/router/index.ts, frontend/src/views/admin/AddProductByAdminView.vue, frontend/src/views/admin/EditProductByAdminView.vue
Close #116 
- 사이드바 접고 펴는 기능을 하는 버튼로고 추가 및 기능 구현 -> 완료
- 로그아웃 기능 구현(임시) -> 완료
- 전체화면 시각적으로 분할 및 개선(메뉴버튼로고,로그아웃 맨바깥페이지/ 사이드바 / 특정메뉴페이지) -> 완료
추가 UI 개선사항 있으시면 계속 알려주세요!
<br/>
=> Feature/116([관리자 페이지] Header 컴포넌트를 수정한다)

frontend/src/assets/main.css, frontend/src/components/ProductCard.vue, frontend/src/components/product/EditProduct.vue, frontend/src/components/profile/DefaultMyPage.vue, frontend/src/components/profile/FilterList.vue, frontend/src/components/profile/ItemList.vue, frontend/src/constants/strings/product.ts, frontend/src/layouts/admin/DefaultSide.vue, frontend/src/layouts/user/DefaultHeader.vue, frontend/src/layouts/user/DefaultLayout.vue, frontend/src/views/user/HomeView.vue, frontend/src/views/user/NotFoundView.vue, frontend/src/views/user/OrderView.vue, frontend/src/views/user/ProductView.vue, frontend/src/views/user/profile/ProfileView.vue
=> Feat/113(디자인 및 색상 변경)

backend/src/main/java/woorifisa/goodfriends/backend/global/config/utils/FileUtils.java, backend/src/main/java/woorifisa/goodfriends/backend/product/application/ProductService.java, backend/src/main/java/woorifisa/goodfriends/backend/product/domain/Product.java, backend/src/main/java/woorifisa/goodfriends/backend/product/domain/ProductImageRepository.java, backend/src/main/java/woorifisa/goodfriends/backend/product/domain/ProductRepository.java, backend/src/main/java/woorifisa/goodfriends/backend/product/dto/response/ProductUpdateResponse.java, backend/src/main/java/woorifisa/goodfriends/backend/product/dto/response/ProductViewOneResponse.java, backend/src/main/java/woorifisa/goodfriends/backend/product/exception/NoSuchImageFileException.java, backend/src/main/java/woorifisa/goodfriends/backend/product/exception/NoSuchProductException.java
Close #122 
nativeQuery와 Postman에서 이미지 파일 전송방법과 관련하여 노션에 문서 작성해놓았습니다! 참고해주세요!
=> Feature/122 (상품 등록/조회/수정/삭제 기능을 리펙토링한다)

frontend/src/layouts/admin/DefaultSide.vue
Close #130 
- div 와 routerview 요소 위치를 재조정합니다. -> 완료
>
=> Feature/130([관리자 페이지] 사이드바 화면 분할 오류를 수정한다.)

frontend/index.html, frontend/src/components/AddressAPI.vue, frontend/src/constants/strings/profile.ts, frontend/src/types/profile.ts, frontend/src/views/user/profile/ProfileView.vue
Close #128 
- 다음 주소찾기 api 적용
- 상세주소 제외 도로명주소로 가져오기
=> Feat/128(주소찾기 API 연결)

frontend/src/components/CommonTable.vue, frontend/src/components/ProductDetailByAdmin.vue, frontend/src/layouts/admin/DefaultSide.vue, frontend/src/router/index.ts, frontend/src/types/product.ts, frontend/src/views/admin/EditProductByAdminView.vue, frontend/src/views/admin/ManageProductView.vue, frontend/src/views/admin/ManageUserView.vue
관리자도 사용자와 같이 상품 페이지를 볼 수 있고, 관리할 수 있도록하는 페이지입니다.
- 상품 관리 페이지를 개발합니다. -> 완료
- 특정 상품을 클릭하면 수정/삭제 화면으로 이동할 수 있습니다. -> 완료
- 상품 관리 페이지에서 등록화면으로 이동할 수 있습니다. -> 완료
>
=> Feature/124([관리자 페이지] 상품 관리 페이지를 개발한다.)

backend/src/main/java/woorifisa/goodfriends/backend/admin/application/AdminService.java, backend/src/main/java/woorifisa/goodfriends/backend/admin/domain/Admin.java, backend/src/main/java/woorifisa/goodfriends/backend/admin/domain/AdminRepository.java, backend/src/main/java/woorifisa/goodfriends/backend/admin/dto/request/AdminLoginRequest.java, backend/src/main/java/woorifisa/goodfriends/backend/admin/dto/response/TokenResponse.java, backend/src/main/java/woorifisa/goodfriends/backend/admin/presentation/AdminController.java, backend/src/main/java/woorifisa/goodfriends/backend/global/config/AuthenticationConfig.java, backend/src/main/java/woorifisa/goodfriends/backend/product/application/ProductService.java, backend/src/main/java/woorifisa/goodfriends/backend/product/domain/Product.java, backend/src/main/java/woorifisa/goodfriends/backend/product/dto/response/ProductViewOneResponse.java, backend/src/main/java/woorifisa/goodfriends/backend/product/presentation/ProductController.java
=> Feature/141([관리자] 상품 등록/조회/수정/삭제 기능을 구현한다.)

backend/src/main/java/woorifisa/goodfriends/backend/auth/application/AuthService.java, backend/src/main/java/woorifisa/goodfriends/backend/auth/application/AuthTokenCreator.java, backend/src/main/java/woorifisa/goodfriends/backend/auth/application/JwtTokenProvider.java, backend/src/main/java/woorifisa/goodfriends/backend/auth/application/TokenCreator.java, backend/src/main/java/woorifisa/goodfriends/backend/auth/domain/AuthToken.java, backend/src/main/java/woorifisa/goodfriends/backend/auth/dto/request/TokenRenewalRequest.java, backend/src/main/java/woorifisa/goodfriends/backend/auth/presentation/AuthController.java
- Close #144 
리프레시 토큰을 통해 새로운 액세스 토큰을 발급하는 기능을 구현했습니다.
=> Feature/76(리프레시 토큰을 통해 새로운 액세스 토큰을 발급)

frontend/src/apis/product.ts, frontend/src/components/AddressAPI.vue, frontend/src/components/CategoryList.vue, frontend/src/components/CommonBanner.vue, frontend/src/components/OrderModal.vue, frontend/src/components/ProductCard.vue, frontend/src/constants/category.ts, frontend/src/constants/strings/error.ts, frontend/src/types/product.ts, frontend/src/views/user/ErrorView.vue, frontend/src/views/user/HomeView.vue, frontend/src/views/user/NotFoundView.vue
Close #155 
- 상품 전체 조회 후 결과값으로 화면에 뿌림
- 만일 api 요청에 오류가 생기면 오류 페이지로 이동 -> 추후 페이지 이동이 아닌 현재 페이지에서 띄워줄 예정
=> Feat/155(상품 전체 조회 api 연결)

frontend/src/constants/strings/admin.ts, frontend/src/views/admin/EditUserInfoView.vue
Close #153 
- 페이지의 디자인 구조를 수정/적용 합니다. -> 완료
- 평점박스 제거 -> 완료
- 사용자 정보란 수정( 생년월일, 메일인증여부, 활성화여부) -> 완료
- 계정삭제시 모달창 팝업-> 완료
>
=> Feature/153([관리자 페이지] 사용자 정보 수정 페이지 구조를 수정한다. )

frontend/src/apis/adminLogin.ts, frontend/src/stores/admin.ts, frontend/src/views/admin/AdminLogin.vue, frontend/src/views/user/ReceiveCodeView.vue
Close #139 
- 관리자 로그인 코드 수정
- 토큰 pinia에서 관리
=> Feature/139(관리자 로그인 수정)

frontend/src/views/admin/ManageDeclarationView.vue
Close #161
피해자 이메일 / 피해자 닉네임 / 상품카테고리 / 상품 이름 / 신고카테고리 / 신고날짜 / 처리상태 순으로 수정한다. -> 완료
>
=> Feature/161([관리자 페이지] 신고관리 페이지 테이블에 표출되는 컬럼을 수정/추가한다. )

backend/src/main/java/woorifisa/goodfriends/backend/order/application/OrderService.java, backend/src/main/java/woorifisa/goodfriends/backend/order/domain/Order.java, backend/src/main/java/woorifisa/goodfriends/backend/order/domain/OrderRepository.java, backend/src/main/java/woorifisa/goodfriends/backend/order/dto/request/OrderSaveRequest.java, backend/src/main/java/woorifisa/goodfriends/backend/order/dto/response/OrderViewAllResponse.java, backend/src/main/java/woorifisa/goodfriends/backend/order/exception/AlreadyOrderedException.java, backend/src/main/java/woorifisa/goodfriends/backend/order/presentation/OrderController.java, backend/src/main/java/woorifisa/goodfriends/backend/product/domain/Order.java
=> Feature/154(상품 주문 등록/조회 기능을 구현한다)

frontend/src/components/CommonBanner.vue
Close #171 
- 기존에는 매번 새로운 이미지를 요청하는 방식
- 현재는 모든 한번에 요청하고 css 속성으로 화면에 안보여주는 방식
=> fix/171(배너 이미지 계속 요청하는 오류 수정)

frontend/src/constants/strings/admin.ts, frontend/src/router/index.ts, frontend/src/views/admin/DeclarationDetailView.vue
Close #169 
- 신고 관리 상세페이지를 개발한다. => 완료
>
=> Feature/169([관리자 페이지] 신고 관리 상세페이지 개발한다. )

backend/src/main/java/woorifisa/goodfriends/backend/global/common/BaseCreateTimeEntity.java, backend/src/main/java/woorifisa/goodfriends/backend/profile/application/ProfileService.java, backend/src/main/java/woorifisa/goodfriends/backend/profile/domain/Profile.java, backend/src/main/java/woorifisa/goodfriends/backend/profile/domain/ProfileRepository.java, backend/src/main/java/woorifisa/goodfriends/backend/profile/dto/request/ProfileUpdateRequest.java, backend/src/main/java/woorifisa/goodfriends/backend/profile/dto/response/ProfileUpdateResponse.java, backend/src/main/java/woorifisa/goodfriends/backend/profile/presentation/ProfileController.java, backend/src/main/java/woorifisa/goodfriends/backend/user/application/UserService.java, backend/src/main/java/woorifisa/goodfriends/backend/user/domain/User.java
- Close #167
사용자(유저)가 본인의 프로필 정보를 수정하는 기능을 구현했습니다.
>
=> Feature/167(프로필 정보를 수정하는 기능 구현)

frontend/src/views/admin/ManageDeclarationView.vue
Close #180 
- 클릭시 해당 리스트의 id값 반환하여 페이지 이동 -> 임시구현
>
=> Feature/180([관리자 페이지] 신고 관리 페이지에서 신고 상세 페이지로 이동을 구현한다.)

frontend/src/apis/index.ts, frontend/src/apis/user/login.ts, frontend/src/constants/localStorage.ts, frontend/src/constants/strings/header.ts, frontend/src/layouts/user/DefaultHeader.vue, frontend/src/stores/userInfo.ts, frontend/src/types/api.ts, frontend/src/views/user/ReceiveCodeView.vue
Close #173 
- 로그아웃 시 API 요청, 토큰 삭제, pinia 초기화
- profile API 연결 이후(사용자 id 얻은 이후) 로그인한 사용자 id로 로그아웃 수정
- 토큰 재발급 API 연결 - 리프레스 토큰을 이용해서 새로운 액세스 토큰 발급하는 기능
=> Feature/173(로그아웃 및 토큰 재발급 API 연결)

backend/src/main/java/woorifisa/goodfriends/backend/auth/exception/EmptyAuthorizationHeaderException.java, backend/src/main/java/woorifisa/goodfriends/backend/auth/exception/NotFoundOAuthTokenException.java, backend/src/main/java/woorifisa/goodfriends/backend/auth/exception/NotFoundTokenException.java, backend/src/main/java/woorifisa/goodfriends/backend/product/application/ProductService.java, backend/src/main/java/woorifisa/goodfriends/backend/product/presentation/ProductController.java
-verifyUser를 통해 해당 상품을 수정 또는 삭제하려는 유저가 해당 상품을 등록한 유저인지 확인
Close #156 
>
=> Feature/156(로그인한 유저에 한한여 상품 등록/수정/삭제 가능하도록 기능 구현)

backend/src/main/java/woorifisa/goodfriends/backend/admin/dto/response/UserLogRecordsResponse.java, backend/src/main/java/woorifisa/goodfriends/backend/admin/exception/NotFoundAdminException.java
Close #193 
- 로그기록 작업 누락된 작업 파일(NotFoundAdminException, UserLogRecordsResponse) develop 브랜치에 merge 진행
>
=> Fix/193(로그 조회 누락된 소스파일 업로드)

backend/src/main/java/woorifisa/goodfriends/backend/admin/application/AdminService.java, backend/src/main/java/woorifisa/goodfriends/backend/admin/domain/AdminRepository.java, backend/src/main/java/woorifisa/goodfriends/backend/admin/presentation/AdminController.java
=> Feature/204(관리자 아이디로 권한 확인 하도록 코드 수정)

backend/src/main/java/woorifisa/goodfriends/backend/admin/application/AdminService.java, backend/src/main/java/woorifisa/goodfriends/backend/product/application/ProductService.java, backend/src/main/java/woorifisa/goodfriends/backend/product/dto/response/ProductViewOneResponse.java, frontend/src/apis/user/product.ts, frontend/src/components/product/EditProduct.vue, frontend/src/types/product.ts, frontend/src/utils/file.ts, frontend/src/utils/validation.ts, frontend/src/views/user/ProductView.vue
Close #170 
- 상품 등록: 로그인 하지 않은 사용자일 경우 메인화면으로 이동
- 상품 수정: 사용자 본인이 올리지 않은 경우에 상품 수정이 아닌 상품 상세페이지로 이동
- 상품 삭제: 사용자 본인이 올리지 않은 경우에 api 요청 막기
=> Feature/170(상품 API 프론트엔드에 연결

backend/src/main/java/woorifisa/goodfriends/backend/auth/application/AuthService.java, backend/src/main/java/woorifisa/goodfriends/backend/auth/application/AuthTokenResponseHandler.java, backend/src/main/java/woorifisa/goodfriends/backend/auth/presentation/AuthController.java, frontend/src/apis/user/login.ts, frontend/src/layouts/user/DefaultHeader.vue
Close #210 
- 프론트
- 로그아웃시 로그인 된 사용자의 id로 로그아웃 할 수 있도록 수정
- 로그아웃 함수의 인자값 id의 타입이 string 이 아닌 number로 수정 (불필요한 타입변환을 없애기 위해)  
- 백엔드
- 기존 DB에 refresh token을 삭제하는 코드 제거
- set cookie를 이용해 refresh token을 만료시키도록 구현
>
=> Fix/210(사용자 로그아웃 코드 수정)

backend/src/main/java/woorifisa/goodfriends/backend/admin/application/AdminAuthenticationFilter.java, backend/src/main/java/woorifisa/goodfriends/backend/admin/application/AdminService.java, backend/src/main/java/woorifisa/goodfriends/backend/admin/domain/Admin.java, backend/src/main/java/woorifisa/goodfriends/backend/admin/domain/AdminRepository.java, backend/src/main/java/woorifisa/goodfriends/backend/admin/dto/request/AdminLoginRequest.java, backend/src/main/java/woorifisa/goodfriends/backend/admin/dto/request/UserUpdateRequest.java, backend/src/main/java/woorifisa/goodfriends/backend/admin/dto/response/UserInfoResponse.java, backend/src/main/java/woorifisa/goodfriends/backend/admin/dto/response/UserLogRecordResponse.java, backend/src/main/java/woorifisa/goodfriends/backend/admin/dto/response/UserLogRecordsResponse.java, backend/src/main/java/woorifisa/goodfriends/backend/admin/exception/NotFoundAdminException.java, backend/src/main/java/woorifisa/goodfriends/backend/admin/presentation/AdminController.java, backend/src/main/java/woorifisa/goodfriends/backend/auth/application/AuthTokenCreator.java, backend/src/main/java/woorifisa/goodfriends/backend/auth/application/JwtTokenProvider.java, backend/src/main/java/woorifisa/goodfriends/backend/auth/application/TokenCreator.java, backend/src/main/java/woorifisa/goodfriends/backend/auth/application/TokenProvider.java, backend/src/main/java/woorifisa/goodfriends/backend/auth/domain/OAuthTokenRepository.java, backend/src/main/java/woorifisa/goodfriends/backend/global/config/SecurityAuthenticationConfig.java, backend/src/main/java/woorifisa/goodfriends/backend/infrastructure/dto/GoogleTokenResponse.java, backend/src/main/java/woorifisa/goodfriends/backend/infrastructure/oauth/uri/GoogleOAuthUri.java, backend/src/main/java/woorifisa/goodfriends/backend/product/domain/Product.java, backend/src/main/java/woorifisa/goodfriends/backend/product/dto/response/ProductDetailResponse.java
Reverts woorifisa-projects/GoodFriends#357
=> Revert "Admin/356(어드민과 관련된 로직 제거)"
